# Autogenerated wrapper script for racket_jll for x86_64-linux-gnu
export racket, raco

JLLWrappers.@generate_wrapper_header("racket")
JLLWrappers.@declare_executable_product(racket)
JLLWrappers.@declare_executable_product(raco)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        racket,
        "bin/racket",
    )

    JLLWrappers.@init_executable_product(
        raco,
        "bin/raco",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
